name: "peaq_network_ev_charging_message_format"
version: "0.1.0"
description: "Protobufs format of charmev message and did document"

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <=3.1.5'

dependencies: 
  fixnum: ^1.0.0
  protobuf: ^3.1.0